apiVersion: v1 
kind: Pod 

metadata:
  name: emptypod 


spec:
  containers:
    - name: cont1
      image: nginx 
      volumeMounts:
        - name: vol1
          mountPath: /suruchi
  volumes:
    - name: vol1
      emptyDir: {}     